import { useEffect, useState } from "react";
import { useParams, useNavigate } from "react-router-dom";
import { ArrowLeft, Printer } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Skeleton } from "@/components/ui/skeleton";
import { PageLoader } from "@/components/ui/spinner";
import { formatNumber } from "@/lib/utils";
import { computeTotals, computeLineItemAmount } from "@/types/challan";
import type { ChallanRecord } from "@/types/challan";
import type { TenantSettings } from "@/types/tenant";
import { api } from "@/lib/api";

export function ChallanPrintPage() {
  const { id } = useParams();
  const navigate = useNavigate();
  const [challan, setChallan] = useState<ChallanRecord | null>(null);
  const [tenant, setTenant] = useState<TenantSettings | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (!id) return;
    api.challans.get(id).then(setChallan).catch((e) => setError(String(e)));
    api.settings.tenant.get().then(setTenant).catch(() => setTenant(null));
    const t = setTimeout(() => window.print(), 400);
    return () => clearTimeout(t);
  }, [id]);

  if (error) {
    return (
      <div className="py-24 text-center text-sm text-destructive">
        {error}
        <div className="mt-4">
          <Button variant="outline" onClick={() => navigate(-1)}>
            <ArrowLeft />
            Back
          </Button>
        </div>
      </div>
    );
  }

  if (!challan || !tenant) return <PageLoader label="Preparing print…" />;

  const totals = computeTotals(challan.lineItems);
  const copies = ["Original For Consignee", "Duplicate For Transporter", "Triplicate For Consignor"];

  return (
    <div className="space-y-4">
      <div className="no-print flex flex-wrap items-center justify-between gap-3 print:hidden">
        <Button variant="outline" size="sm" onClick={() => navigate(-1)}>
          <ArrowLeft />
          Back
        </Button>
        <Button size="sm" onClick={() => window.print()}>
          <Printer />
          Print Challan
        </Button>
      </div>

      <div className="mx-auto max-w-3xl space-y-4 print:max-w-none">
        {copies.map((copy) => (
          <PrintCopy key={copy} copy={copy} challan={challan} tenant={tenant} totals={totals} />
        ))}
        <p className="text-center text-xs text-muted-foreground print:hidden">Generated by DyeAI · {new Date().toLocaleString("en-IN")}</p>
      </div>

      <style>{`
        @media print {
          body { -webkit-print-color-adjust: exact; }
          @page { size: A4; margin: 12mm; }
        }
      `}</style>
    </div>
  );
}

function PrintCopy({
  copy,
  challan,
  tenant,
  totals,
}: {
  copy: string;
  challan: ChallanRecord;
  tenant: TenantSettings;
  totals: ReturnType<typeof computeTotals>;
}) {
  const h = challan.header;
  const isOutgoing = challan.documentType === "outgoing";
  return (
    <section className="break-after-page rounded-lg border bg-white p-5 text-[11px] leading-relaxed text-neutral-900 print:rounded-none print:border-0 print:p-0 print:shadow-none">
      {/* Header */}
      <div className="flex items-start justify-between border-b-2 border-neutral-900 pb-2">
        <div>
          <h1 className="text-base font-bold uppercase">{tenant.companyName}</h1>
          <p className="text-neutral-600">{tenant.address}</p>
          <p className="text-neutral-600">GSTIN: {tenant.gstin} · {tenant.state}</p>
          {tenant.email && <p className="text-neutral-600">{tenant.email}</p>}
        </div>
        <div className="text-right">
          <p className="text-sm font-bold uppercase tracking-wide">
            {isOutgoing ? "Outgoing Challan" : "Incoming Challan"}
          </p>
          <p className="text-[10px] uppercase">Transport / Delivery Challan</p>
        </div>
      </div>

      {/* Doc meta */}
      <div className="mt-2 flex flex-wrap items-center justify-between gap-2">
        <p>
          <span className="font-semibold">Challan No:</span> {h.challanNo ?? "—"}
        </p>
        <p>
          <span className="font-semibold">Date:</span> {h.challanDate}
        </p>
        <p>
          <span className="font-semibold">E-Way No:</span> {h.eWayNo || "—"}
        </p>
        <p>
          <span className="font-semibold">Vehicle No:</span> {h.vehicleNo}
        </p>
      </div>

      {/* Parties */}
      <div className="mt-3 grid grid-cols-2 gap-3">
        <div className="border border-neutral-300 p-2">
          <p className="text-[10px] font-bold uppercase">Billed To</p>
          <p className="font-semibold">{h.billing.name}</p>
          <p>{h.billing.address}</p>
          <p>GSTIN: {h.billing.gstin || "—"}</p>
          <p>
            State: {h.billing.state} ({h.billing.stateCode})
          </p>
        </div>
        <div className="border border-neutral-300 p-2">
          <p className="text-[10px] font-bold uppercase">Shipped To</p>
          <p className="font-semibold">{h.shipping.name}</p>
          <p>{h.shipping.address}</p>
          <p>GSTIN: {h.shipping.gstin || "—"}</p>
          <p>
            State: {h.shipping.state} ({h.shipping.stateCode})
          </p>
        </div>
      </div>

      {/* Line items */}
      <table className="mt-3 w-full border-collapse text-[11px]">
        <thead>
          <tr className="border border-neutral-900 bg-neutral-100">
            <th className="border border-neutral-400 p-1 text-left">#</th>
            <th className="border border-neutral-400 p-1 text-left">Lot No.</th>
            <th className="border border-neutral-400 p-1 text-left">Particulars</th>
            <th className="border border-neutral-400 p-1 text-left">Process</th>
            <th className="border border-neutral-400 p-1 text-left">Colour</th>
            <th className="border border-neutral-400 p-1 text-left">Depth</th>
            <th className="border border-neutral-400 p-1 text-left">HSN</th>
            <th className="border border-neutral-400 p-1 text-right">Rolls</th>
            <th className="border border-neutral-400 p-1 text-right">Weight</th>
            <th className="border border-neutral-400 p-1 text-right">Rate</th>
            <th className="border border-neutral-400 p-1 text-right">Amount</th>
          </tr>
        </thead>
        <tbody>
          {challan.lineItems.map((item, i) => (
            <tr key={item.id}>
              <td className="border border-neutral-300 p-1">{i + 1}</td>
              <td className="border border-neutral-300 p-1">{item.lotNo ?? "—"}</td>
              <td className="border border-neutral-300 p-1">{item.particulars ?? "—"}</td>
              <td className="border border-neutral-300 p-1">{item.processName ?? "—"}</td>
              <td className="border border-neutral-300 p-1">{item.colour ?? "—"}</td>
              <td className="border border-neutral-300 p-1">{item.depth ?? "—"}</td>
              <td className="border border-neutral-300 p-1">{item.hsnCode ?? "—"}</td>
              <td className="border border-neutral-300 p-1 text-right">{item.roll ?? "—"}</td>
              <td className="border border-neutral-300 p-1 text-right">{item.weight ?? "—"}</td>
              <td className="border border-neutral-300 p-1 text-right">{item.rate ?? "—"}</td>
              <td className="border border-neutral-300 p-1 text-right">{computeLineItemAmount(item).toFixed(2)}</td>
            </tr>
          ))}
          <tr className="font-semibold">
            <td colSpan={7} className="border border-neutral-300 p-1 text-right">
              Total
            </td>
            <td className="border border-neutral-300 p-1 text-right">{formatNumber(totals.totalRoll)}</td>
            <td className="border border-neutral-300 p-1 text-right">{formatNumber(totals.totalWeight)}</td>
            <td className="border border-neutral-300 p-1" />
            <td className="border border-neutral-300 p-1 text-right">₹{totals.totalApproxAmount.toFixed(2)}</td>
          </tr>
        </tbody>
      </table>

      {/* Terms + signature */}
      <div className="mt-3 flex items-end justify-between gap-8">
        <div className="space-y-0.5 text-neutral-700">
          <p>
            <span className="font-semibold">Remarks:</span> {isOutgoing ? "Goods accepted subject to our inspection on arrival." : "Received in good condition."}
          </p>
          <p>
            <span className="font-semibold">Carrier:</span> {h.transporter ?? "—"}
          </p>
          {isOutgoing && h.dispatchDate && (
            <p>
              <span className="font-semibold">Dispatch Date:</span> {h.dispatchDate}
            </p>
          )}
          {challan.header.linkedIncomingChallanIds?.length ? (
            <p>
              <span className="font-semibold">Linked Incoming:</span> {challan.header.linkedIncomingChallanIds.length} challan(s)
            </p>
          ) : null}
        </div>
        <div className="text-center">
          <p className="mb-8">Authorised Signature</p>
          <div className="w-40 border-t border-neutral-900 pt-1 text-[10px] text-neutral-600">
            {tenant.companyName}
          </div>
        </div>
      </div>

      {/* Copy marker */}
      <div className="mt-2 text-center">
        <span className="inline-block rounded border border-neutral-400 px-3 py-0.5 text-[10px] font-semibold uppercase">
          {copy}
        </span>
      </div>
    </section>
  );
}