"""sync: raw_json on documents, sync_tombstones

Revision ID: d3c7f3ae21f1
Revises: da7e9c61d8fd
Create Date: 2026-09-23 14:21:49.450159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.models.base


revision: str = 'd3c7f3ae21f1'
down_revision: Union[str, None] = 'da7e9c61d8fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sync_tombstones',
    sa.Column('table_name', sa.String(length=60), nullable=False),
    sa.Column('row_id', app.models.base.DBUUID(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('table_name', 'row_id'),
    sa.UniqueConstraint('table_name', 'row_id', name='uq_sync_tombstone')
    )
    op.add_column('dyeing_documents', sa.Column('raw_json', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dyeing_documents', 'raw_json')
    op.drop_table('sync_tombstones')
    # ### end Alembic commands ###