"""initial schema: users, masters, dyeing documents

Revision ID: da7e9c61d8fd
Revises: 
Create Date: 2026-09-23 11:38:54.754036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.models.base


revision: str = 'da7e9c61d8fd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', app.models.base.DBUUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('role', sa.String(length=30), server_default='Operator', nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('categories',
    sa.Column('id', app.models.base.DBUUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_by', app.models.base.DBUUID(), nullable=True),
    sa.Column('updated_by', app.models.base.DBUUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('colour_groups',
    sa.Column('id', app.models.base.DBUUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_by', app.models.base.DBUUID(), nullable=True),
    sa.Column('updated_by', app.models.base.DBUUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('colours',
    sa.Column('hex', sa.String(length=7), nullable=True),
    sa.Column('id', app.models.base.DBUUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_by', app.models.base.DBUUID(), nullable=True),
    sa.Column('updated_by', app.models.base.DBUUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('customers',
    sa.Column('gstin', sa.String(length=15), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('state', sa.String(length=80), nullable=True),
    sa.Column('state_code', sa.String(length=5), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('id', app.models.base.DBUUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_by', app.models.base.DBUUID(), nullable=True),
    sa.Column('updated_by', app.models.base.DBUUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_customers_gstin'), 'customers', ['gstin'], unique=False)
    op.create_table('depths',
    sa.Column('id', app.models.base.DBUUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_by', app.models.base.DBUUID(), nullable=True),
    sa.Column('updated_by', app.models.base.DBUUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('dyeing_types',
    sa.Column('id', app.models.base.DBUUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_by', app.models.base.DBUUID(), nullable=True),
    sa.Column('updated_by', app.models.base.DBUUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('hsn_codes',
    sa.Column('id', app.models.base.DBUUID(), nullable=False),
    sa.Column('code', sa.String(length=12), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), server_default='0.00', nullable=False),
    sa.Column('created_by', app.models.base.DBUUID(), nullable=True),
    sa.Column('updated_by', app.models.base.DBUUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hsn_codes_code'), 'hsn_codes', ['code'], unique=True)
    op.create_table('processes',
    sa.Column('contact_name', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('id', app.models.base.DBUUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_by', app.models.base.DBUUID(), nullable=True),
    sa.Column('updated_by', app.models.base.DBUUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tax_accounts',
    sa.Column('gst_rate', sa.Numeric(precision=5, scale=2), server_default='0.00', nullable=False),
    sa.Column('id', app.models.base.DBUUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_by', app.models.base.DBUUID(), nullable=True),
    sa.Column('updated_by', app.models.base.DBUUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('dyeing_documents',
    sa.Column('id', app.models.base.DBUUID(), nullable=False),
    sa.Column('document_type', sa.String(length=16), nullable=False),
    sa.Column('challan_no', sa.String(length=60), nullable=False),
    sa.Column('serial_no', sa.String(length=60), nullable=True),
    sa.Column('document_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='saved', nullable=False),
    sa.Column('customer_id', app.models.base.DBUUID(), nullable=True),
    sa.Column('category_id', app.models.base.DBUUID(), nullable=True),
    sa.Column('tax_account_id', app.models.base.DBUUID(), nullable=True),
    sa.Column('vehicle_no', sa.String(length=40), nullable=True),
    sa.Column('through', sa.String(length=200), nullable=True),
    sa.Column('through_dyeing', sa.String(length=200), nullable=True),
    sa.Column('remarks', sa.String(length=1000), nullable=True),
    sa.Column('issue_to_tubitor', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('issue_to_redyeing', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('non_paid', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('redyeing_ref', sa.String(length=120), nullable=True),
    sa.Column('tubitor_ref', sa.String(length=120), nullable=True),
    sa.Column('eway_no', sa.String(length=40), nullable=True),
    sa.Column('shipping', sa.String(length=200), nullable=True),
    sa.Column('total_rolls', sa.Numeric(precision=18, scale=3), server_default='0.000', nullable=False),
    sa.Column('total_qty', sa.Numeric(precision=18, scale=3), server_default='0.000', nullable=False),
    sa.Column('gross_amount', sa.Numeric(precision=18, scale=2), server_default='0.00', nullable=False),
    sa.Column('round_off', sa.Numeric(precision=18, scale=2), server_default='0.00', nullable=False),
    sa.Column('net_amount', sa.Numeric(precision=18, scale=2), server_default='0.00', nullable=False),
    sa.Column('created_by', app.models.base.DBUUID(), nullable=True),
    sa.Column('updated_by', app.models.base.DBUUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("document_type IN ('RECEIPT', 'ISSUE')", name='ck_dyeing_document_type'),
    sa.CheckConstraint("status IN ('draft', 'saved')", name='ck_dyeing_document_status'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tax_account_id'], ['tax_accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_type', 'challan_no', name='uq_dyeing_document_type_challan')
    )
    op.create_index('ix_dyeing_documents_challan_no', 'dyeing_documents', ['challan_no'], unique=False)
    op.create_index('ix_dyeing_documents_customer_id', 'dyeing_documents', ['customer_id'], unique=False)
    op.create_index('ix_dyeing_documents_document_date', 'dyeing_documents', ['document_date'], unique=False)
    op.create_index('ix_dyeing_documents_document_type', 'dyeing_documents', ['document_type'], unique=False)
    op.create_index('ix_dyeing_documents_vehicle_no', 'dyeing_documents', ['vehicle_no'], unique=False)
    op.create_table('items',
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('hsn_id', app.models.base.DBUUID(), nullable=True),
    sa.Column('id', app.models.base.DBUUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_by', app.models.base.DBUUID(), nullable=True),
    sa.Column('updated_by', app.models.base.DBUUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['hsn_id'], ['hsn_codes.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('rate_cards',
    sa.Column('id', app.models.base.DBUUID(), nullable=False),
    sa.Column('customer_id', app.models.base.DBUUID(), nullable=True),
    sa.Column('process', sa.String(length=120), nullable=True),
    sa.Column('depth', sa.String(length=80), nullable=True),
    sa.Column('fabric_quality', sa.String(length=120), nullable=True),
    sa.Column('value', sa.Numeric(precision=18, scale=2), server_default='0.00', nullable=False),
    sa.Column('created_by', app.models.base.DBUUID(), nullable=True),
    sa.Column('updated_by', app.models.base.DBUUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shades',
    sa.Column('id', app.models.base.DBUUID(), nullable=False),
    sa.Column('colour_id', app.models.base.DBUUID(), nullable=False),
    sa.Column('depth_id', app.models.base.DBUUID(), nullable=False),
    sa.Column('created_by', app.models.base.DBUUID(), nullable=True),
    sa.Column('updated_by', app.models.base.DBUUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['colour_id'], ['colours.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['depth_id'], ['depths.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('colour_id', 'depth_id')
    )
    op.create_table('dyeing_document_items',
    sa.Column('id', app.models.base.DBUUID(), nullable=False),
    sa.Column('dyeing_document_id', app.models.base.DBUUID(), nullable=False),
    sa.Column('line_no', sa.Integer(), nullable=False),
    sa.Column('lot_no', sa.String(length=60), nullable=True),
    sa.Column('item_id', app.models.base.DBUUID(), nullable=True),
    sa.Column('dyeing_type_id', app.models.base.DBUUID(), nullable=True),
    sa.Column('colour_id', app.models.base.DBUUID(), nullable=True),
    sa.Column('colour_group_id', app.models.base.DBUUID(), nullable=True),
    sa.Column('process_id', app.models.base.DBUUID(), nullable=True),
    sa.Column('rolls', sa.Numeric(precision=18, scale=3), server_default='0.000', nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=3), server_default='0.000', nullable=False),
    sa.Column('rate', sa.Numeric(precision=18, scale=2), server_default='0.00', nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), server_default='0.00', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['colour_group_id'], ['colour_groups.id'], ),
    sa.ForeignKeyConstraint(['colour_id'], ['colours.id'], ),
    sa.ForeignKeyConstraint(['dyeing_document_id'], ['dyeing_documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dyeing_type_id'], ['dyeing_types.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['process_id'], ['processes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dyeing_document_id', 'line_no', name='uq_dyeing_document_item_line')
    )
    op.create_index('ix_dyeing_document_items_colour_id', 'dyeing_document_items', ['colour_id'], unique=False)
    op.create_index('ix_dyeing_document_items_dyeing_document_id', 'dyeing_document_items', ['dyeing_document_id'], unique=False)
    op.create_index('ix_dyeing_document_items_item_id', 'dyeing_document_items', ['item_id'], unique=False)
    op.create_index('ix_dyeing_document_items_lot_no', 'dyeing_document_items', ['lot_no'], unique=False)
    # ### end Alembic commands ###

    seed_users(op.get_bind())


def seed_users(bind) -> None:
    """Seed the four demo users (password: Password123!)."""
    import uuid

    password_hash = (
        "pbkdf2_sha256$200000$ZHllYWktc2VlZC1zYWx0$"
        "dvkUDlkwP8wdDu4c/Hd5HHvKBlmmpkeqRvrp7f4q3Cs="
    )
    users_table = sa.table(
        "users",
        sa.column("id", sa.Uuid()),
        sa.column("name", sa.String()),
        sa.column("email", sa.String()),
        sa.column("phone", sa.String()),
        sa.column("role", sa.String()),
        sa.column("password_hash", sa.String()),
    )
    bind.execute(
        users_table.insert(),
        [
            {
                "id": uuid.uuid4(),
                "name": "Haninder Singh",
                "email": "haninder.singh@punjabdyeingmills.in",
                "phone": None,
                "role": "Admin",
                "password_hash": password_hash,
            },
            {
                "id": uuid.uuid4(),
                "name": "Arjun Patel",
                "email": "arjun.patel@punjabdyeingmills.in",
                "phone": None,
                "role": "Supervisor",
                "password_hash": password_hash,
            },
            {
                "id": uuid.uuid4(),
                "name": "Vikram Singh",
                "email": "vikram.singh@punjabdyeingmills.in",
                "phone": None,
                "role": "Operator",
                "password_hash": password_hash,
            },
            {
                "id": uuid.uuid4(),
                "name": "Anita Desai",
                "email": "anita.desai@punjabdyeingmills.in",
                "phone": None,
                "role": "Accounts",
                "password_hash": password_hash,
            },
        ],
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_dyeing_document_items_lot_no', table_name='dyeing_document_items')
    op.drop_index('ix_dyeing_document_items_item_id', table_name='dyeing_document_items')
    op.drop_index('ix_dyeing_document_items_dyeing_document_id', table_name='dyeing_document_items')
    op.drop_index('ix_dyeing_document_items_colour_id', table_name='dyeing_document_items')
    op.drop_table('dyeing_document_items')
    op.drop_table('shades')
    op.drop_table('rate_cards')
    op.drop_table('items')
    op.drop_index('ix_dyeing_documents_vehicle_no', table_name='dyeing_documents')
    op.drop_index('ix_dyeing_documents_document_type', table_name='dyeing_documents')
    op.drop_index('ix_dyeing_documents_document_date', table_name='dyeing_documents')
    op.drop_index('ix_dyeing_documents_customer_id', table_name='dyeing_documents')
    op.drop_index('ix_dyeing_documents_challan_no', table_name='dyeing_documents')
    op.drop_table('dyeing_documents')
    op.drop_table('tax_accounts')
    op.drop_table('processes')
    op.drop_index(op.f('ix_hsn_codes_code'), table_name='hsn_codes')
    op.drop_table('hsn_codes')
    op.drop_table('dyeing_types')
    op.drop_table('depths')
    op.drop_index(op.f('ix_customers_gstin'), table_name='customers')
    op.drop_table('customers')
    op.drop_table('colours')
    op.drop_table('colour_groups')
    op.drop_table('categories')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###